version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    ".gitignore",
    "config.*",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-xfrm-esp-avoid-in-place-decrypt-on-shared-skb-frags.patch",
]
SPDX-FileCopyrightText = "linux contributors"
SPDX-License-Identifier = "GPL-2.0-only"
